### ISSUE TITLE
SDK tries to authenticate by showing SFSafariViewController from view controller whose view is not in the view hierarchy

### ISSUE THREAD

**Issue by mommyme** [pinterest/ios-pdk#93]
My rootViewController is a container controller, and my app does some 'fancy footwork' upon launch to get the correct controller in place.

When I try to authenticate Pinterest from an established view controller, it must be trying to present the login controller from the rootViewController, whose view is not in the view hierarchy. Is there any way I can specify the UIViewController from which the SFSafariViewController should be presented? Please?

`Warning: Attempt to present <SFSafariViewController: 0x7fc502c86b40> on <LaunchViewController: 0x7fc501720d20> whose view is not in the window hierarchy!`

**Comment by mommyme** [comment]
This is what should be fixed. I don't know how to do a pull request. Sorry.
```
+ (void)openURL:(NSURL *)url
{
    NSString *scheme = [[url scheme] lowercaseString];
    if (NSClassFromString(@"SFSafariViewController") != nil && ([scheme isEqualToString:@"http"] || [scheme isEqualToString:@"https"])) {
        //UIViewController *viewController = [[[UIApplication sharedApplication] keyWindow] rootViewController];
        UIViewController *viewController = [UIApplication sharedApplication].keyWindow.rootViewController;
        while (viewController.presentedViewController)
        {
            viewController = viewController.presentedViewController;
        }
        SFSafariViewController *safariViewController = [[SFSafariViewController alloc] initWithURL:url];
        [viewController presentViewController:safariViewController animated:YES completion:nil];
    } else if ([[UIApplication sharedApplication] canOpenURL:url]) {
        [[UIApplication sharedApplication] openURL:url];
    }
}

```

**Comment by mommyme** [comment]
Also,

In `handleCallbackURL:`, making the following substitution would be very helpful in dismissing the controller presented in `openURL:`

```
            //UIViewController *mainViewController = [[[UIApplication sharedApplication] keyWindow] rootViewController];
            UIViewController *mainViewController = [UIApplication sharedApplication].keyWindow.rootViewController;
            while (mainViewController.presentedViewController)
            {
                if ([[mainViewController presentedViewController] isKindOfClass:[SFSafariViewController class]]) {
                    break;
                }
                mainViewController = mainViewController.presentedViewController;
            }
            
            if ([[mainViewController presentedViewController] isKindOfClass:[SFSafariViewController class]]) {
                [mainViewController dismissViewControllerAnimated:YES completion:nil];
            }
```

**Comment by mommyme** [comment]
Is this something you think you might want to change/update/fix or am I mistaken in some way?

**Comment by mommyme** [comment]
Any thoughts on this issue?

**Comment by jinthreek89** [comment]
@mommyme Your code is very helpful for me.
I was saw this issue on my project. But I have fixed with your code.
Thanks so much.

**Comment by oshitub123** [comment]
can you put that on swift 3 for xcode 8.3.2

**Comment by oshitub123** [comment]
because i have tried so much but now i can't do it

**Comment by HiramKarim** [comment]
Anyone has the solution for this in Swift 3?
 This error remains on Pinterest SDK and gets me frustrated =\

Thanks!

**Comment by oshitub123** [comment]
yeah @HiramKarim  send me a code, maybe you have the same troble than me, i was calling the method from  a mehtod but ih have to be called into button action

**Comment by vpuli** [comment]
Same error happens with Google SDK and OAuth, i cant perform a segue since SFAuthenticationViewController is not in the window hierarchy. Any one know how I can fix this in Swift?

**Comment by HiramKarim** [comment]
Hi guys, after many attempts to authenticate using Pinterest SDK for iOS I decide to call the api methods to get the access token and the user information, I know, it should be using the SDK but the Pinterest team seems doesn’t have any interest to fix this issue on iOS. Try using the api calls using webviews With your keys and will work well...for now. 

Regards ~
